project_id = "qryyixzwyrqkgkkgrnay"

[functions.send-booking-notification]
verify_jwt = false

[functions.admin-bookings]
verify_jwt = false

[functions.get-payment-details]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false
