project_id = "qryyixzwyrqkgkkgrnay"

[functions.send-booking-notification]
verify_jwt = false

[functions.admin-bookings]
verify_jwt = false

[functions.get-payment-details]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.check-rate-limit]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.get-turnstile-key]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false
